extends SceneTree
const State=preload("res://scripts/lol2/cave_roach_population_state.gd")
const Goal=preload("res://scripts/lol2/hive_ai_goal_choice.gd")
const Action=preload("res://scripts/lol2/hive_ai_action_choice.gd")
func _initialize() -> void:
	var fixture: Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/cave_roach_ai_choice_native.json"))
	var goal:=Goal.new();var action:=Action.new()
	assert(goal.configure(fixture.contracts.goals).is_empty())
	assert(action.configure(fixture.contracts.actions).is_empty())
	var state:=State.initial()
	assert(State.first_contact(state,1140))
	var stats: Array=state.actors["25"].stats.duplicate()
	var before:=state.duplicate(true)
	# A valid goal result followed by unavailable action scoring must be atomic.
	assert(State.choose_pending(state,"25",stats,goal,Action.new()).has("error"))
	assert(state==before)
	assert(State.choose_pending(state,"25",stats.slice(0,29),goal,action).has("error"))
	assert(state==before)
	var result:=State.choose_pending(state,"25",stats,goal,action)
	assert(result.chosen and result.goal.chosen and result.action.chosen)
	assert(state.actors["25"].a9==6 and state.actors["25"].ab==0)
	assert(state.actors["25"].a8==14 and state.actors["25"].aa==9)
	var restored:=State.canonical(JSON.parse_string(JSON.stringify(state)))
	assert(State.validate(restored).is_empty())
	assert(State.commit(restored,"25",1) and State.commit(state,"25",1))
	assert(restored==state and restored.actors["25"].a8==6 and restored.actors["25"].aa==0)
	before=state.duplicate(true)
	assert(not State.choose_pending(state,"40",stats,goal,action).chosen)
	assert(state==before)
	state.actors["25"].b5=13
	before=state.duplicate(true)
	assert(not State.choose_pending(state,"25",stats,goal,action).chosen and state==before)
	state.actors["25"].health=0;state.actors["25"].a8=15
	before=state.duplicate(true)
	assert(State.choose_pending(state,"25",stats,goal,action).has("error") and state==before)
	assert(State.choose_pending(state,"36",stats,goal,action).has("error") and state==before)
	print("PASS: source-scored Roach pending choices, goal-before-action, deferred JSON commit, atomic failure, blocked/unrequested/dead/unknown actors")
	quit()
