extends SceneTree
const State=preload("res://scripts/lol2/cave_eyes_state.gd")
func _initialize() -> void:
	var src:=State.source();var state:=State.initial(src)
	assert(State.validate(state,src).is_empty())
	assert(State.use(state) and not State.use(state))
	State.advance(state,src,0.05)
	var restored:=State.canonical(JSON.parse_string(JSON.stringify(state)))
	assert(State.validate(restored,src).is_empty())
	State.advance(state,src,7.0);State.advance(restored,src,7.0)
	assert(state==restored and state.phase=="moving")
	var fine:=State.initial(src);State.use(fine)
	for i in range(423): State.advance(fine,src,1.0/60.0)
	assert(Vector3(fine.position[0],fine.position[1],fine.position[2]).distance_to(Vector3(state.position[0],state.position[1],state.position[2]))<0.05)
	State.advance(state,src,100.0)
	assert(state.phase=="removed" and state.index==6 and State.validate(state,src).is_empty())
	var bad:=state.duplicate(true);bad.clock=NAN;assert(not State.validate(bad,src).is_empty())
	bad=state.duplicate(true);bad.index=1.5;assert(not State.validate(bad,src).is_empty())
	bad=State.initial(src);bad.position[0]+=1;assert(not State.validate(bad,src).is_empty())
	print("PASS cave eyes source use, saved partial path, split ticks, terminal120ticks, repeat and malformed save rejection")
	quit()
