extends SceneTree
const Quests = preload("res://scripts/lol2/act_one_quest_state.gd")
const HiveSave = preload("res://scripts/lol2/hive_save.gd")
const JungleSave = preload("res://scripts/lol2/jungle_save.gd")
func _initialize(): run.call_deferred()
func run():
	var path := "user://tests/hive_quest_%d.json" % Time.get_ticks_usec()
	var jungle_path := "user://tests/jungle_quest_%d.json" % Time.get_ticks_usec()
	var hive = load("res://scenes/lol2/hive_review.tscn").instantiate()
	root.add_child(hive)
	var actor = hive.get_node("ConversationReview")
	actor.set_process(false)
	var envelope := {"inventory":{"collected":[JungleSave.Museum.SWORD],"equipped_item":JungleSave.Museum.SWORD,"equipped_armor":""},"quests":Quests.initial()}
	envelope.quests.monastery.globals.GV_MET_BACATTA = 1
	envelope.quests.monastery.locals.Met_Dawn = 1
	assert(hive.apply_area_handoff(envelope).is_empty())
	envelope.inventory.collected.clear()
	assert(hive.carried_inventory.collected.size() == 1)
	assert(not actor.begin())
	hive.player.position = Vector3(-1218,-203,-8725)
	actor.check_room_contact()
	assert(actor.room_entered)
	assert(hive.quicksave(path).is_empty())
	assert(actor.restore_quest_checkpoint(Quests.initial()).is_empty())
	assert(not actor.room_entered and not actor.begin())
	assert(hive.quickload(path).is_empty())
	assert(actor.room_entered and not actor.started)
	var invalid_room: Dictionary = actor.quest_checkpoint()
	invalid_room.hive_room_entered = 1
	assert(not actor.restore_quest_checkpoint(invalid_room).is_empty())
	assert(actor.room_entered and not actor.started)
	assert(actor.begin())
	var legacy_quest: Dictionary = actor.quest_checkpoint()
	legacy_quest.erase("hive_room_entered")
	assert(actor.restore_quest_checkpoint(legacy_quest).is_empty() and actor.room_entered)
	var contradiction: Dictionary = actor.quest_checkpoint()
	contradiction.hive_room_entered = false
	assert(not actor.restore_quest_checkpoint(contradiction).is_empty())
	actor.advance(1.25)
	assert(hive.quicksave(path).is_empty())
	var saved := HiveSave.read_save(path)
	assert(saved.error.is_empty() and saved.state.quests.shared_flag_38 == 1)
	assert(saved.state.quests.monastery.locals.Met_Dawn == 1)
	assert(not JungleSave.read_save(path).error.is_empty())
	var original := FileAccess.get_file_as_bytes(path)
	for bad in [null,{},true]:
		var state: Dictionary = saved.state.duplicate(true)
		state.quests = bad
		assert(not hive.apply_save(state).is_empty())
		assert(not HiveSave.write_save(path,state).is_empty())
		assert(FileAccess.get_file_as_bytes(path) == original)
	for pair in [["elapsed",NAN],["elapsed",INF],["elapsed",-1],["elapsed",100],["section_cursor",true],["section_cursor",1.5],["section_cursor",4],["started",false],["completed",true]]:
		var state: Dictionary = saved.state.duplicate(true)
		state.quests.conversation[pair[0]] = pair[1]
		assert(not hive.apply_save(state).is_empty())
		assert(actor.elapsed == 1.25 and not hive.is_physics_processing())
	var inconsistent: Dictionary = saved.state.duplicate(true)
	inconsistent.quests.shared_flag_38 = 0
	assert(not hive.apply_save(inconsistent).is_empty())
	actor.advance(1000)
	assert(actor.completed and hive.is_physics_processing())
	assert(hive.quickload(path).is_empty())
	assert(actor.started and not actor.completed and actor.elapsed == 1.25 and actor.frame == 18)
	assert(not hive.is_physics_processing() and actor.audio.playing)
	assert(actor.shared_flags[38] == 1 and not actor.begin())
	actor.advance(1000)
	assert(hive.quicksave(path).is_empty())
	var handoff: Dictionary = hive.area_handoff()
	hive.free()
	var jungle = load("res://scenes/lol2/jungle_walkthrough.tscn").instantiate()
	root.add_child(jungle)
	jungle.set_physics_process(false)
	assert(jungle.apply_area_handoff(handoff).is_empty())
	handoff.quests.shared_flag_38 = 0
	assert(jungle.quest_state.shared_flag_38 == 1)
	assert(jungle.quicksave(jungle_path).is_empty())
	var jungle_state := JungleSave.read_save(jungle_path)
	assert(jungle_state.error.is_empty() and jungle_state.state.quests.conversation.completed)
	assert(jungle_state.state.quests.monastery.globals.GV_MET_BACATTA == 1)
	var legacy: Dictionary = jungle_state.state.duplicate(true)
	legacy.erase("quests")
	assert(jungle.apply_save(legacy).is_empty() and jungle.quest_state == Quests.initial())
	assert(jungle.quickload(jungle_path).is_empty())
	handoff = jungle.area_handoff()
	jungle.free()
	hive = load("res://scenes/lol2/hive_review.tscn").instantiate()
	root.add_child(hive)
	actor = hive.get_node("ConversationReview")
	assert(hive.apply_area_handoff(handoff).is_empty())
	assert(actor.completed and actor.frame == 912 and not actor.audio.playing and not actor.begin())
	assert(hive.carried_inventory.equipped_item == JungleSave.Museum.SWORD)
	assert(hive.area_handoff().quests.monastery.locals.Met_Dawn == 1)
	assert(hive.is_physics_processing())
	assert(not HiveSave.read_save(jungle_path).error.is_empty())
	hive.free()
	DirAccess.remove_absolute(path)
	DirAccess.remove_absolute(jungle_path)
	print("Quest saves: active audio/frame resume, invalid state safety, legacy saves, completed state and Hive/jungle handoff passed")
	quit()
