extends SceneTree
const Audio=preload("res://scripts/lol2/hive_boulder_audio_state.gd")
const Surface=preload("res://scripts/lol2/hive_boulder_sequence.gd")
const Actors=preload("res://scripts/lol2/hive_boulder_actor_state.gd")
func _initialize() -> void:
	var fixtures: Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/hive_boulder_audio_spatial_native.json"))
	for row in fixtures.rows:
		var p: Array=row.position
		assert(Audio.spatial_factor(Vector3(p[0],p[1],p[2]),row.near,row.far)==int(row.factor))
	assert(Audio.drift("30",Audio.LENGTHS["30"]-0.005,0.005)<0.011)
	assert(Audio.drift("close",1.0,0.0)==1.0)
	var state:=Audio.initial()
	var surface:=Surface.initial()
	var actors:=Actors.initial()
	assert(Audio.validate_context(state,surface,actors).is_empty())
	var before:=surface.duplicate()
	Surface.begin(surface)
	Surface.advance(surface,0.5)
	Audio.advance(state,before,surface,actors,0.5)
	assert(state.clocks.close==0.5 and Audio.active(state,"close"))
	before=surface.duplicate()
	var result:=Surface.advance(surface,0.75)
	for group in result.groups: Actors.apply_group(actors,group)
	Audio.advance(state,before,surface,actors,0.75)
	assert(is_equal_approx(state.clocks["30"],1.25-Surface.CLOSE_SECONDS))
	assert(Audio.validate_context(state,surface,actors).is_empty())
	for i in range(100):
		var restored:=Audio.canonical(JSON.parse_string(JSON.stringify(state,"",true,true)))
		before=surface.duplicate()
		result=Surface.advance(surface,0.125)
		for group in result.groups: Actors.apply_group(actors,group)
		Audio.advance(state,before,surface,actors,0.125)
		Audio.advance(restored,before,surface,actors,0.125)
		for key in Audio.LENGTHS: assert(absf(state.clocks[key]-restored.clocks[key])<0.000000001)
		assert(Audio.validate_context(state,surface,actors).is_empty())
	# A 2.159-second exit clip must outlive the surface's 2-second cap.
	before=surface.duplicate()
	var delta: float=2.05-float(surface.elapsed)
	Surface.advance(surface,delta)
	Audio.advance(state,before,surface,actors,delta)
	assert(surface.elapsed==2.0 and Audio.active(state,"exit") and is_equal_approx(state.clocks.exit,2.05))
	var restored:=Audio.canonical(JSON.parse_string(JSON.stringify(state,"",true,true)))
	before=surface.duplicate()
	Audio.advance(state,before,surface,actors,0.2)
	Audio.advance(restored,before,surface,actors,0.2)
	assert(not Audio.active(state,"exit") and not Audio.active(restored,"exit"))
	actors.actors["30"].rolling=false
	Audio.advance(state,surface,surface,actors,0.01)
	assert(not Audio.active(state,"30") and Audio.active(state,"31"))
	var stable:=state.duplicate(true)
	for invalid in [-1.0,NAN,INF]: assert(not Audio.advance(state,surface,surface,actors,invalid) and state==stable)
	for key in Audio.LENGTHS:
		var bad:=state.duplicate(true)
		bad.clocks[key]=NAN
		assert(not Audio.validate(bad).is_empty())
		bad=state.duplicate(true)
		bad.clocks.erase(key)
		assert(not Audio.validate(bad).is_empty())
	var legacy:=Audio.legacy(surface,actors)
	assert(not Audio.active(legacy,"close") and not Audio.active(legacy,"exit") and not Audio.active(legacy,"30") and Audio.active(legacy,"31"))
	# Crossing the entire surface chain in one host tick retains the true tail.
	state=Audio.initial();before=Surface.initial();surface=Surface.initial();actors=Actors.initial()
	Surface.begin(surface)
	result=Surface.advance(surface,20.0)
	for group in result.groups: Actors.apply_group(actors,group)
	Audio.advance(state,before,surface,actors,20.0)
	assert(not Audio.active(state,"close") and not Audio.active(state,"exit"))
	print("PASS saved audio clock continuation, true exit tail beyond surface cap, separate owners, coarse crossings, malformed clocks and legacy no-cue replay")
	quit()
