extends SceneTree
const State=preload("res://scripts/lol2/jungle_chief_hut_state.gd")
func _initialize() -> void:
	var src:=State.source();var s:=State.initial()
	assert(State.validate(s).is_empty())
	assert(State.ignite(s,src).is_empty())
	assert(State.raise_gate(s,src,1).is_empty())
	assert(not State.raise_gate(s,src,2).is_empty() and s.locals["9"]==1)
	assert(State.raise_gate(s,src,2).is_empty())
	State.observe_pool(s,src);assert(s.locals["11"]==1)
	State.advance(s,src,1);assert(s.floor_heights["3751"]==-20 and s.floor_heights["3742"]==-25)
	assert(not State.strike(s,src).is_empty())
	assert(State.strike(s,src).is_empty() and State.ignite(s,src).is_empty())
	State.advance(s,src,0.4);assert(s.floor_presets["3742"]==30)
	assert(not State.ignite(s,src).is_empty())
	State.advance(s,src,7.5)
	assert(State.validate(s).is_empty())
	var restored:=State.canonical(JSON.parse_string(JSON.stringify(s)))
	assert(State.validate(restored).is_empty())
	State.advance(s,src,8.5);State.advance(restored,src,8.5)
	if s!=restored or s.phase!="movie": print("Checkpoint mismatch: ",s," vs ",restored)
	assert(s==restored and s.phase=="movie")
	var effects:=State.advance(s,src,4)
	assert(s.phase=="done" and State.validate(s).is_empty())
	assert(effects.filter(func(e): return str(e.get("raw",""))=="ce00000000ff").size()==1)
	assert(State.advance(s,src,20).is_empty())
	assert(State.village_entry(s,src,1).is_empty())
	assert(not State.village_entry(s,src,0).is_empty() and State.village_entry(s,src,0).is_empty())
	assert(State.validate(s).is_empty())
	var bad:=s.duplicate(true);bad.phase="idle";assert(not State.validate(bad).is_empty())
	bad=s.duplicate(true);bad.floor_heights["3742"]=NAN;assert(not State.validate(bad).is_empty())
	# Source p124: Spark needs rock owner state1, which only raised water gives. Low-water ignition is refused;
	# raising the water afterwards (g20500) admits it. The strike's selector never sets the owner state.
	s=State.initial();State.observe_pool(s,src);State.strike(s,src);State.advance(s,src,0.5)
	assert(s.locals["10"]==1 and s.rock==0 and s.rock_elapsed==State.ROCK_TIME)
	assert(State.ignite(s,src).is_empty() and s.phase=="idle")
	State.raise_gate(s,src,2);State.observe_pool(s,src);assert(s.locals["11"]==1 and s.rock==1 and s.floor_presets["3742"]==30)
	assert(not State.ignite(s,src).is_empty() and s.phase=="fire")
	print("PASS chief hut prerequisites, raised water/oil, ignition, fire/movie checkpoint, one soul outcome, guarded village release, low-water branch and invalid saves.")
	quit()
