extends SceneTree
func _initialize() -> void:
	var scene = load("res://scripts/lol2/museum_sword_transfer.gd").new()
	root.add_child(scene)
	_run.call_deferred(scene)
func _run(scene: Node3D) -> void:
	assert(scene.available)
	scene.set_process(false)
	assert(scene.phase == "waiting" and not scene.table_sword.visible)
	var completions := [0]
	scene.sequence_finished.connect(func(): completions[0] += 1)
	scene.restart()
	scene.advance(3.0)
	assert(scene.phase == "placing" and scene.actor.position == scene.GOAL)
	scene.advance(0.749)
	assert(scene.held.visible and not scene.table_sword.visible)
	scene.advance(0.0011)
	assert(not scene.held.visible and scene.table_sword.visible)
	assert(scene.table_sword.position == scene.TABLE_SWORD)
	scene.advance(100)
	assert(scene.phase == "complete" and completions[0] == 1)
	assert(not scene.skeleton.flip_h)
	var previous_texture = scene.skeleton.texture
	scene.advance(0.125)
	assert(scene.skeleton.texture != previous_texture and completions[0] == 1)
	var saved: Dictionary = scene.checkpoint()
	var saved_texture = scene.skeleton.texture
	scene.advance(0.25)
	scene.restore_checkpoint(saved)
	assert(scene.skeleton.texture == saved_texture and completions[0] == 1)
	scene.advance(7 * 0.125)
	assert(scene.skeleton.texture == saved_texture and completions[0] == 1)
	scene.restart()
	assert(scene.held.visible and not scene.table_sword.visible and scene.actor.position == scene.START)
	assert(scene.skeleton.flip_h and scene.idle_elapsed == 0)
	print("Museum transfer passed: endpoint, activation boundary, completion and restart")
	scene.free()
	var museum = load("res://scenes/lol2/museum_review.tscn").instantiate()
	root.add_child(museum)
	assert(museum.ready_for_review and museum.sword_transfer.available)
	assert(museum.museum_gate.available and not museum.museum_gate.target_open)
	museum.sword_transfer.restart()
	museum.sword_transfer.advance(7.624)
	assert(not museum.museum_gate.target_open)
	museum.sword_transfer.advance(0.002)
	assert(museum.museum_gate.target_open)
	museum.museum_gate.advance(1.2)
	assert(is_equal_approx(museum.museum_gate.progress, 1.0))
	assert(is_equal_approx(museum.museum_gate.pivot.rotation.y, -19660.0 * TAU / 65536.0))
	museum.museum_gate.open()
	museum.museum_gate.advance(0.5)
	assert(is_equal_approx(museum.museum_gate.progress, 1.0))
	museum.sword_transfer.restart()
	assert(not museum.museum_gate.target_open and museum.museum_gate.progress == 0)
	print("Museum gate passed: delayed opening, native target, repeat request and reset")
	paused = true
	var held_time: float = museum.sword_transfer.elapsed
	await create_timer(0.05).timeout
	assert(museum.sword_transfer.elapsed == held_time)
	paused = false
	for i in range(90): await physics_frame
	assert(museum.player.is_on_floor())
	assert(museum.sword_transfer.elapsed > held_time)
	print("Museum integration passed: source scene load, paused sequence, resumed sequence and arrival floor")
	museum.free()
	quit()
