extends SceneTree
## Headless Champion Stone effect state. No scene, inventory, or combat edits.
const Effects = preload("res://scripts/lol2/player_item_effects.gd")
const Ancient = preload("res://scripts/lol2/hive_ancient_stone.gd")
const Aloe = preload("res://scripts/lol2/cave_aloe.gd")
const STONE_A := "museum:item8:Champion_Stone"
const STONE_B := "museum:item9:Champion_Stone"

func gates(held: bool = true, gate0: int = 0, flags: int = 0, caller_bit: bool = false, gate4: int = 0) -> Dictionary:
	return {"held": held, "gate_223d0": gate0, "action_flags": flags, "caller_bit0": caller_bit, "gate_223d4": gate4}

func _initialize() -> void:
	assert(Effects.BONUS == 20 and Effects.HIGH_WORD_EXTEND == 3600)
	assert(Effects.CHAMPION_DEFINITION == 123 and Effects.CHAMPION_IDENTITY == 4234311831 and Effects.CHAMPION_HANDLER == 4)
	var idle := Effects.empty()
	assert(Effects.melee_bonus(idle).bonus == 0)
	assert(Effects.augment_stat39c(8, idle).stat39c == 8)
	assert(Effects.restore({"version": 0, "active": false, "timer": 0}).has("error"))
	assert(Effects.restore({"version": 2, "active": false, "timer": 0}).has("error"))
	assert(Effects.restore({"version": 1, "active": 1, "timer": 0}).has("error"))
	assert(Effects.restore({"version": 1, "active": false, "timer": -1}).has("error"))
	assert(Effects.restore({"version": 1, "active": false, "timer": 4294967296}).has("error"))
	assert(Effects.restore({"version": 1, "active": false}).has("error"))
	assert(Effects.use(idle, [STONE_A], STONE_A, {"held": true}).has("error"))
	assert(Effects.admits(STONE_A, {"held": false, "gate_223d0": 1, "action_flags": 0, "caller_bit0": false}).reason == "No held item.")
	assert(Effects.admits(STONE_A, gates(true, 1)).reason == "Use gate 223D0 is set.")
	assert(Effects.admits(STONE_A, gates(true, 0, 0x01000000)).reason == "Action flag 2279A bit 24 is set.")
	assert(Effects.admits(STONE_A, gates(true, 0, 0xffffffff)).reason == "Action flag 2279A bit 24 is set.")
	assert(Effects.admits(STONE_A, gates(true, 0, 0xfe000000)).usable)
	assert(Effects.admits(STONE_A, gates(true, 0, 0x00800000)).usable)
	assert(not Effects.admits(STONE_A, gates(true, 0, 0, true)).usable)
	var ancient := Effects.describe(Ancient.ITEM)
	var aloe := Effects.describe(Aloe.item_id(791, 1))
	assert(ancient.kind == "ancient_stone" and ancient.handler == 6 and not ancient.usable)
	assert(aloe.kind == "cave_aloe" and aloe.handler == 9 and not aloe.usable)
	assert(not Effects.admits(Ancient.ITEM, gates()).usable and Effects.admits(Ancient.ITEM, gates()).admitted)
	assert(Effects.describe("museum:item11:Fine_Longsword").kind == "none")
	var original_pack := [STONE_A, "museum:item11:Fine_Longsword", STONE_B]
	var original_state := Effects.empty()
	var blocked := Effects.use(original_state, original_pack, Ancient.ITEM, gates())
	assert(not blocked.applied and blocked.rejected_by == "effect" and blocked.inventory == original_pack and original_pack.size() == 3)
	var missing := Effects.use(original_state, ["museum:item11:Fine_Longsword"], STONE_A, gates())
	assert(not missing.applied and missing.rejected_by == "pack" and not missing.state.active)
	var first := Effects.use(original_state, original_pack, STONE_A, gates())
	assert(original_state.timer == 0 and original_pack[0] == STONE_A)
	assert(first.applied and first.consumed and first.activated and first.source_result == 1)
	assert(first.bonus_before == 0 and first.bonus == 20)
	assert(first.state.timer == 3600 << 16 and first.state.active)
	assert(first.inventory == ["museum:item11:Fine_Longsword", STONE_B])
	var second := Effects.use(first.state, first.inventory, STONE_B, gates())
	assert(second.applied and second.consumed and not second.activated and second.bonus_before == 20 and second.bonus == 20)
	assert(second.state.timer == 7200 << 16 and second.inventory == ["museum:item11:Fine_Longsword"])
	var kept := [STONE_A]
	var blocked_consume := Effects.use(Effects.empty(), kept, STONE_A, gates(true, 0, 0, false, 255))
	assert(blocked_consume.applied and not blocked_consume.consumed and blocked_consume.inventory == [STONE_A] and kept == [STONE_A])
	assert(blocked_consume.bonus == 20 and blocked_consume.state.timer == 3600 << 16)
	var wrapped := Effects.use({"version": 1, "active": false, "timer": (65535 << 16) | 7}, [STONE_A], STONE_A, gates())
	assert(wrapped.state.timer == (3599 << 16) | 7)
	var partial := Effects.maintain(first.state, 100)
	assert(not partial.expired and partial.bonus == 20 and partial.timer == (3600 << 16) - 100)
	var saved := Effects.checkpoint(partial.state)
	assert(Effects.restore(saved.checkpoint).state.timer == partial.timer)
	var exact := Effects.maintain(partial.state, partial.timer)
	assert(exact.expired and exact.bonus == 0 and exact.timer == 0 and not exact.state.active)
	var over := Effects.maintain(first.state, (3600 << 16) + 50)
	assert(over.expired and over.timer == 0xffffffce)
	var resumed := Effects.use(over.state, [STONE_B], STONE_B, gates())
	assert(resumed.state.active and resumed.state.timer == (3599 << 16) | 0xffce)
	var zeroed := {"version": 1, "active": true, "timer": 0}
	assert(Effects.maintain(zeroed, 0).expired and zeroed.timer == 0 and zeroed.active)
	assert(not Effects.maintain({"version": 1, "active": true, "timer": 1}, 0).expired)
	var wrapped_delta := Effects.maintain({"version": 1, "active": true, "timer": 5}, 0xffffffff)
	assert(not wrapped_delta.expired and wrapped_delta.timer == 6)
	var inactive := {"version": 1, "active": false, "timer": 4}
	assert(Effects.maintain(inactive, 1).has("error") and inactive.timer == 4)
	var armed := Effects.augment_stat39c(8, first.state)
	assert(armed.base == 8 and armed.bonus == 20 and armed.stat39c == 28)
	var rolled := Effects.augment_stat39c(0xffffffff, first.state)
	assert(rolled.base == 0xffffffff and rolled.stat39c == 19)
	var negative := Effects.augment_stat39c(-20, first.state)
	assert(negative.base == 0xffffffec and negative.stat39c == 0)
	assert(Effects.augment_stat39c(1.5, first.state).has("error"))
	assert(Effects.melee_bonus(exact.state).bonus == 0)
	print("PASS champion stone effects: admission, consume, +20, timer extend/expiry, stat39c, exclusions")
	quit()
