#!/usr/bin/env python3
"""Join mapped area-change groups to source region/actor/prop/control/movable event owners."""
import hashlib,json,struct
from collections import Counter
from pathlib import Path
from build_game_atlas import ROOT,parse_mix,u32,section
GAME=Path('/home/bob/lol2_out/museum_capture_20260913/game')

def events(blob,start):
    cursor=start
    while True:
        if cursor+2>len(blob):raise ValueError(f'Event list outside section: {start}/{cursor}/{len(blob)}')
        length,kind=blob[cursor:cursor+2]
        if not length or not kind:return
        if length<2 or cursor+length>len(blob):raise ValueError('Invalid event length')
        body=blob[cursor:cursor+length]
        following=blob[cursor+length:cursor+length+4]
        predicate=int.from_bytes(following[2:4],'little') if len(following)==4 and following[1]==19 else None
        yield cursor,kind,body,predicate
        cursor+=length

def collect_owners(raw,archive_offset,region_count):
    region_ofs,_,region_events=section(raw,0x38,0x80,1)
    object_ofs,_,object_events=section(raw,0x40,0x88,1)
    desc_ofs,desc_count,descriptors=section(raw,0xa4,0xac,26)
    lists={}
    for index in range(desc_count):
        offset=struct.unpack_from('<H',descriptors,index*26+10)[0]
        lists.setdefault(offset,[]).append(index)
    owners=[];counts=Counter()
    for offset,indices in lists.items():
        for cursor,kind,body,predicate in events(region_events,offset):
            counts['descriptor_events']+=1
            if kind!=12:continue
            if len(body)<8:raise ValueError('Truncated region group event')
            group,region,event,value=struct.unpack_from('<HHBB',body,2)
            assert region<region_count
            owners.append(dict(stream=0,group=group,owner_kind='region',owner=region,descriptors=indices,event=event,value=value,predicate=predicate,archive_offset=archive_offset+region_ofs+cursor))
    for label,of,cf,stride in [('actor',0x1c,0x68,56),('prop',0x14,0x60,37),('control',0x18,0x64,33),('movable',0x24,0x70,41)]:
        _,count,records=section(raw,of,cf,stride)
        for index in range(count):
            offset=struct.unpack_from('<H',records,index*stride+12)[0]
            for cursor,kind,body,predicate in events(object_events,offset):
                counts[label+'_events']+=1
                if kind not in [2,3,4,5,6,8,9,10]:continue
                if len(body)<4:raise ValueError('Truncated object group event')
                group=struct.unpack_from('<H',body,2)[0]
                owners.append(dict(stream=1,group=group,owner_kind=label,owner=index,event=kind,value=int.from_bytes(body[4:6],'little') if len(body)>=6 else None,predicate=predicate,archive_offset=archive_offset+object_ofs+cursor))
    return owners,counts

def main():
    inventory=json.loads((ROOT/'docs/game-source-inventory.json').read_text())
    areas=[]
    for area in inventory['areas']:
        archive=(GAME/area['source']['file']).read_bytes()
        assert hashlib.sha256(archive).hexdigest()==area['source']['sha256']
        entry=next(e for e in parse_mix(archive) if e['key']==area['source']['geometry_key'])
        raw=archive[entry['offset']:entry['offset']+entry['size']]
        assert hashlib.sha256(raw).hexdigest()==area['source']['geometry_sha256']
        owners,counts=collect_owners(raw,entry['offset'],area['counts']['regions'])
        transitions=[]
        for transition in area['transitions']:
            matched=[o for o in owners if o['stream']==transition['stream'] and o['group']==transition['group']]
            transitions.append(dict(transition,direct_owners=matched,ownership='direct source event' if matched else 'not directly bound'))
        areas.append(dict(id=area['id'],source=area['source'],event_counts=dict(counts),transitions=transitions))
        print(area['id'],len(transitions),'transitions;',sum(bool(t['direct_owners']) for t in transitions),'directly owned')
    result=dict(version=1,scope='Direct event ownership of source transition groups; predicates, event scheduling and indirect callers are not executed.',areas=areas)
    (ROOT/'docs/game-transition-owners.json').write_text(json.dumps(result,indent=2)+'\n')
    lines = ['# Source area-transition owners', '',
             'Generated by `tools/audit_game_transition_owners.py` from the pinned15-area source inventory.', '',
             'This joins area-change command groups to direct region/prop/actor/control/movable event references. It does not execute predicates, prove route availability, or classify required versus optional content. Missing direct owners may be reached indirectly.', '',
             '| Area | Transition commands | Direct event owners | Still indirect/unbound |',
             '| --- | ---: | ---: | ---: |']
    for area in areas:
        count=len(area['transitions']);matched=sum(bool(t['direct_owners']) for t in area['transitions'])
        lines.append(f'| {area["id"]} | {count} | {matched} | {count-matched} |')
    for area in areas:
        lines += ['', '## '+area['id'], '', '| Destination / entry | Stream / group | Direct source trigger |', '| --- | --- | --- |']
        for transition in area['transitions']:
            descriptions=[]
            for owner in transition['direct_owners']:
                predicate='no attached predicate' if owner['predicate'] is None else f'predicate{owner["predicate"]}'
                event_label = 'event' if owner['owner_kind']=='region' else 'record kind'
                descriptions.append(f'{owner["owner_kind"]}{owner["owner"]}, {event_label}{owner["event"]}, value{owner.get("value")}, {predicate}')
            lines.append(f'| L{transition["destination_level"]} / {transition["destination_entry"]} | {transition["stream"]} / {transition["group"]} | '+('; '.join(descriptions) or 'Indirect caller or unbound owner')+' |')
    lines += ['', '## Verification and limits', '',
              'Archive and geometry hashes match the coverage inventory. Event sections and records are bounded; known region references are in range. Both region and object event lists are walked from source owners. Source offsets are retained in `game-transition-owners.json`.', '',
              'Kind8 group offset2 and argument-match offset4 follow the checked AE526 handler. `tools/verify_cave_exit_event.py` additionally replays cave prop447 argument973 through group4030 enqueue arguments, binding its L3/entry1 exit. The event producer remains separate.', '',
              'Event ownership is an implementation lead. An attached predicate index is not a decoded gameplay condition. No attached predicate does not prove unconditional reachability. Source scripts may enqueue a group indirectly, and later commands can affect whether an area change occurs.', '',
              'The local atlas highlights direct source exit regions/objects in pink and provides an exit locator. Run the ownership audit after the source inventory exists, then regenerate the atlas. Original map geometry stays in the local atlas output.', '']
    (ROOT/'docs/game-transition-owners.md').write_text('\n'.join(lines))
    print('PASS:',sum(len(a['transitions']) for a in areas),'transitions audited across',len(areas),'areas')
if __name__=='__main__':main()
