#!/usr/bin/env python3
"""Index direct source event and literal command references for mapped actors."""
import hashlib,json,struct
from collections import Counter
from build_game_atlas import ROOT,parse_mix,section,SIZES
from audit_game_transition_owners import GAME,events

def groups(blob):
    rows=[];cursor=0
    while cursor<len(blob):
        length=SIZES.get(blob[cursor]);assert length and cursor+length<=len(blob)
        rows.append((cursor,blob[cursor:cursor+length]));cursor+=length
    assert b''.join(body for _,body in rows)==blob
    index=0
    while index<len(rows):
        offset,head=rows[index];grouped=head[0]==240;count=head[4] if grouped else 1;first=index+int(grouped)
        children=rows[first:first+count];assert len(children)==count and all(b[0]!=240 for _,b in children)
        yield offset,children
        index=first+count

def main():
    source=json.loads((ROOT/'docs/game-actors.json').read_text());areas=[]
    for area in source['areas']:
        archive=(GAME/area['source']['file']).read_bytes();assert hashlib.sha256(archive).hexdigest()==area['source']['sha256']
        ge=next(e for e in parse_mix(archive) if e['key']==area['source']['geometry_key']);geo=archive[ge['offset']:ge['offset']+ge['size']]
        assert hashlib.sha256(geo).hexdigest()==area['source']['geometry_sha256']
        by_actor={a['actor']:dict(actor=a['actor'],definition=a['definition'],name=a['name'],events=[],addressed_commands=[]) for a in area['actors']}
        group_offsets={};unresolved=Counter();command_count=0
        for stream,(of,sf) in enumerate([(0x3c,0x84),(0x44,0x8c)]):
            start,_,blob=section(geo,of,sf,1);parsed=list(groups(blob));group_offsets[stream]={offset for offset,_ in parsed}
            for group,commands in parsed:
                for offset,body in commands:
                    command_count+=1
                    if body[1]!=2:continue
                    target=struct.unpack_from('<H',body,2)[0]
                    if target not in by_actor:
                        unresolved[target]+=1;continue
                    by_actor[target]['addressed_commands'].append(dict(stream=stream,group=group,command_offset=offset,opcode=body[0],archive_offset=ge['offset']+start+offset))
        start,_,blob=section(geo,0x40,0x88,1);_,count,placements=section(geo,0x1c,0x68,56)
        for actor in range(count):
            offset=struct.unpack_from('<H',placements,actor*56+12)[0]
            for cursor,kind,body,predicate in events(blob,offset):
                if kind not in [2,3,4,5,6,8,9,10]:continue
                assert len(body)>=4;group=struct.unpack_from('<H',body,2)[0];assert group in group_offsets[1],(area['id'],actor,kind,group)
                by_actor[actor]['events'].append(dict(kind=kind,group=group,predicate=predicate,archive_offset=ge['offset']+start+cursor))
        actors=list(by_actor.values());areas.append(dict(id=area['id'],source=area['source'],commands_scanned=command_count,nonliteral_or_unbound_actor_targets=dict(sorted(unresolved.items())),actors=actors))
        print(area['id'],sum(bool(a['events']) for a in actors),'actors with direct event groups;',sum(bool(a['addressed_commands']) for a in actors),'with literal command references')
    scope='Static direct source references only: known actor event kinds2/3/4/5/6/8/9/10 to stream1 groups and commands whose target kind2/word names an in-range literal actor index. Shared event lists can repeat a group across actors. Special/runtime target selectors remain unbound. Does not execute events, predicates, command effects, indirect calls, activation or outcomes.'
    (ROOT/'docs/game-actor-scripts.json').write_text(json.dumps(dict(version=1,scope=scope,areas=areas),indent=2)+'\n')
    lines=['# Source actor script dependencies','','Generated by `tools/audit_game_actor_scripts.py`. This turns named placements into bounded implementation leads. '+scope,'','| Area | Actors with event groups | Actors addressed by literal commands | Commands scanned |','| --- | ---: | ---: | ---: |']
    for area in areas:lines.append(f'| {area["id"]} | {sum(bool(a["events"]) for a in area["actors"])} | {sum(bool(a["addressed_commands"]) for a in area["actors"])} | {area["commands_scanned"]} |')
    for area in areas:
        lines+=['','## '+area['id'],'','| Actor / source label | Direct event group count | Addressed command count | Attached predicate indices |','| --- | ---: | ---: | --- |']
        for actor in area['actors']:
            if not actor['events'] and not actor['addressed_commands']:continue
            predicates=sorted({e['predicate'] for e in actor['events'] if e['predicate'] is not None})
            lines.append(f'| {actor["actor"]} / {actor["name"]} | {len(actor["events"])} | {len(actor["addressed_commands"])} | '+(', '.join(map(str,predicates)) or 'None attached')+' |')
    lines+=['','Full source group/command offsets and archive positions are in `game-actor-scripts.json`. No direct references does not mean an actor is optional, inert or unused. A command reference does not mean that command executes in every playthrough. Next, follow one actor\'s predicates and source groups to observable encounter requirements.','']
    (ROOT/'docs/game-actor-scripts.md').write_text('\n'.join(lines))
    print('PASS:',sum(a['commands_scanned'] for a in areas),'non-header commands;',sum(len(x['events']) for a in areas for x in a['actors']),'actor event references;',sum(len(x['addressed_commands']) for a in areas for x in a['actors']),'literal actor command references')
if __name__=='__main__':main()
