#!/usr/bin/env python3
"""Extract defense bytes and mitigation records for admitted Act1 equipment."""
import hashlib,json,struct
from pathlib import Path
from prepare_hive_wax import entry,u32
ROOT=Path(__file__).resolve().parents[1]

def main():
    raw=entry('GLOBAL.MIX',3984507021)
    digest=hashlib.sha256(raw).hexdigest()
    assert digest=='b399b5c8bfea3597293a3237f30f45985efa2dd88d2dc29d5d18ca7488f60891'
    base,n=u32(raw,4),u32(raw,0x34)
    states=base+n*91+4;frames=states+u32(raw,states-4)*16+4;names=frames+u32(raw,frames-4)*12
    mapping={'museum:prop280:Prism':(7,'8-Prism'),'jungle:kelsrick:Fine_Longsword':(5,'6-Fine longswd'),'cave:guard38:Short_Sword':(4,'5-Short swd'),'cave:guard39:Short_Sword':(4,'5-Short swd'),'cave:guard52:Short_Sword':(4,'5-Short swd'),'cave:guard53:Short_Sword':(4,'5-Short swd'),'cave:guard52:Guard_Shield':(37,'38-Guard shield'),'cave:guard53:Guard_Shield':(37,'38-Guard shield'),'cave:guard54:prop1013:Short_Sword':(4,'5-Short swd'),'cave:guard54:actor54:Short_Sword':(4,'5-Short swd'),
    'cave:captain:Short_Sword':(4,'5-Short swd'),'cave:captain:Burnt_Chain':(36,'37-Brnt Chain'),
        'museum:item11:Fine_Longsword':(5,'6-Fine longswd'),'museum:item10:Mail_Shirt':(40,'41-Mail shirt'),
        'jungle:item51:Th_Dagger':(9,'10-Th Dagger'),'jungle:weapon_shop:Short_Sword':(4,'5-Short swd'),
        'jungle:weapon_shop:Long_Arm':(6,'7-Long arm'),'museum:prop153:Long_arm':(6,'7-Long arm'),'jungle:weapon_shop:Firestorm':(8,'9-Firestorm'),
        'jungle:weapon_shop:Gargoyle_Bracers':(41,'42-Gargoyle br'),
        'jungle:kityara:Empty_hand':(29,'30-Empty hand'),
        'hive:control121:Reaver_of_GO':(17,'18-Reaver of GO'),
        'hive:prop214:Net_of_Exile':(25,'26-Net of Exile'),
        'jungle:magic_shop:Dag_Light':(27,'28-Dag Light'),'jungle:magic_shop:Tho_fixed':(20,'21-Tho fixed')}
    for record in [144,145,146,147,148,149,641]:mapping[f'cave:prop{record}:harvest1:Stalagmite']=(0,'1-Stalagmite')
    rows={}
    for identity,(index,name) in mapping.items():
        assert raw[names+index*30:names+index*30+24].split(b'\0')[0].decode()==name
        d=raw[base+index*91:base+(index+1)*91]
        descriptor=[[d[0x47+i],*struct.unpack_from('<HH',d,0x4b+i*4)] for i in range(4)]
        rows[identity]=dict(definition=index,name=name,source_identity=u32(d,24),defense=struct.unpack_from('<b',d,0x41)[0],descriptors=[r for r in descriptor if any(r)],definition_sha256=hashlib.sha256(d).hexdigest())
    assert rows['jungle:weapon_shop:Firestorm']['defense']==5
    (ROOT/'scripts/lol2/item_defense_data.gd').write_text('extends RefCounted\n## Generated by prepare_act_one_item_defenses.py from pinned original definitions.\nconst ITEMS := '+json.dumps(rows)+'\n')
    (ROOT/'docs/act-one-item-defenses.json').write_text(json.dumps(dict(definitions_sha256=digest,items=rows,scope='Pinned definition names/identities, signed byte41 and descriptor47. Equipment slot ordering and item possession are separate; native equipment sum proof is verify_hive_equipment_stats.py.'),indent=2)+'\n')
    print('PASS',len(rows),'equippable identities; Firestorm defense5')
if __name__=='__main__':main()
